# Generated by Django 3.2.5 on 2021-08-12 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_name', models.CharField(blank=True, default='Saved Route', max_length=50, null=True)),
                ('origin_name', models.CharField(max_length=225)),
                ('origin_lat', models.FloatField()),
                ('origin_lon', models.FloatField()),
                ('destin_name', models.CharField(max_length=225)),
                ('destin_lat', models.FloatField()),
                ('destin_lon', models.FloatField()),
                ('stops', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favourites',
                'managed': True,
            },
        ),
    ]
