# Generated by Django 3.2.4 on 2021-07-11 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bus', '0001_initial'),
        ('users', '0002_alter_savedpath_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpath',
            name='end_id',
            field=models.ForeignKey(default='8220DB000002', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Bus.stop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedpath',
            name='start_id',
            field=models.ForeignKey(default='8220DB000003', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Bus.stop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedpath',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
