# Generated by Django 3.2.4 on 2021-07-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_savedpath_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedpath',
            options={},
        ),
    ]
