# Generated by Django 3.2.5 on 2021-07-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_savedpath_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='savedPath',
        ),
    ]
