# Generated by Django 3.2.5 on 2021-08-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_delete_savedpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_name', models.CharField(blank=True, default='Saved Route', max_length=50, null=True)),
                ('origin_name', models.CharField(max_length=225)),
                ('origin_lat', models.FloatField()),
                ('origin_lon', models.FloatField()),
                ('destin_name', models.CharField(max_length=225)),
                ('destin_lat', models.FloatField()),
                ('destin_lon', models.FloatField()),
                ('stops', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'favourites',
                'managed': False,
            },
        ),
    ]
