# Generated by Django 3.2.4 on 2021-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('monday', models.IntegerField(blank=True, null=True)),
                ('tuesday', models.IntegerField(blank=True, null=True)),
                ('wednesday', models.IntegerField(blank=True, null=True)),
                ('thursday', models.IntegerField(blank=True, null=True)),
                ('friday', models.IntegerField(blank=True, null=True)),
                ('saturday', models.IntegerField(blank=True, null=True)),
                ('sunday', models.IntegerField(blank=True, null=True)),
                ('start_date', models.IntegerField(blank=True, null=True)),
                ('end_date', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True, null=True)),
                ('exception_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calendar_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('agency_id', models.TextField(blank=True, null=True)),
                ('route_short_name', models.TextField(blank=True, null=True)),
                ('route_long_name', models.TextField(blank=True, null=True)),
                ('route_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('shape_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('shape_pt_lat', models.FloatField(blank=True, null=True)),
                ('shape_pt_lon', models.FloatField(blank=True, null=True)),
                ('shape_pt_sequence', models.IntegerField(blank=True, null=True)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shapes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(blank=True, max_length=225, null=True)),
                ('stop_lat', models.FloatField(blank=True, null=True)),
                ('stop_lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('arrival_time', models.TextField()),
                ('stop_sequence', models.IntegerField(blank=True, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=225, null=True)),
                ('route_id', models.TextField(blank=True, null=True)),
                ('route_short_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stop_times',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('trip_headsign', models.TextField(blank=True, null=True)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trips',
                'managed': False,
            },
        ),
    ]
