# Generated by Django 3.2.5 on 2021-08-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('monday', models.IntegerField(blank=True, null=True)),
                ('tuesday', models.IntegerField(blank=True, null=True)),
                ('wednesday', models.IntegerField(blank=True, null=True)),
                ('thursday', models.IntegerField(blank=True, null=True)),
                ('friday', models.IntegerField(blank=True, null=True)),
                ('saturday', models.IntegerField(blank=True, null=True)),
                ('sunday', models.IntegerField(blank=True, null=True)),
                ('start_date', models.IntegerField(blank=True, null=True)),
                ('end_date', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calendar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('dt', models.IntegerField(primary_key=True, serialize=False)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('weather_main', models.CharField(blank=True, max_length=30, null=True)),
                ('weather_description', models.CharField(blank=True, max_length=60, null=True)),
                ('weather_icon', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'current_weather',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('agency_id', models.TextField(blank=True, null=True)),
                ('route_short_name', models.TextField(blank=True, null=True)),
                ('route_long_name', models.TextField(blank=True, null=True)),
                ('route_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(blank=True, max_length=225, null=True)),
                ('stop_lat', models.FloatField(blank=True, null=True)),
                ('stop_lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stops',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('shape_id', models.CharField(max_length=225)),
                ('trip_headsign', models.TextField(blank=True, null=True)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
                ('route_id', models.ForeignKey(db_column='route_id', on_delete=django.db.models.deletion.CASCADE, to='Bus.route')),
                ('service_id', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='Bus.calendar')),
            ],
            options={
                'db_table': 'trips',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('arrival_time', models.TextField()),
                ('stop_sequence', models.IntegerField(blank=True, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=225, null=True)),
                ('stop_id', models.ForeignKey(db_column='stop_id', on_delete=django.db.models.deletion.CASCADE, to='Bus.stop')),
                ('trip_id', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, to='Bus.trip')),
            ],
            options={
                'db_table': 'stop_times',
                'managed': True,
                'unique_together': {('trip_id', 'stop_sequence')},
            },
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True, null=True)),
                ('exception_type', models.IntegerField(blank=True, null=True)),
                ('service_id', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='Bus.calendar')),
            ],
            options={
                'db_table': 'calendar_dates',
                'managed': True,
                'unique_together': {('service_id', 'date')},
            },
        ),
    ]
